// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/9/25 13:31:28
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/jiuxi/Desktop/ying-recite/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jiuxi/Desktop/ying-recite/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jiuxi/Desktop/ying-recite/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jiuxi/Desktop/ying-recite/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jiuxi/Desktop/ying-recite/plugins/**/*.{js,ts,mjs}","C:/Users/jiuxi/Desktop/ying-recite/composables/**/*.{js,ts,mjs}","C:/Users/jiuxi/Desktop/ying-recite/utils/**/*.{js,ts,mjs}","C:/Users/jiuxi/Desktop/ying-recite/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jiuxi/Desktop/ying-recite/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jiuxi/Desktop/ying-recite/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;